service: my-graphql-api

provider:
  name: aws
  runtime: nodejs16.x
plugins:
  - serverless-offline

 
functions:
  graphql:
    handler: dist/handler.graphqlHandler
    timeout: 30
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
